allowBuilds:
  '@parcel/watcher': false
  core-js: false
  chokidar: true
  sass: true
  sass-embedded: true
  esbuild: true
  secp256k1: false
blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
strictDepBuilds: true
trustPolicy: no-downgrade
