name: Docker publish

on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"
      - "develop"
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
      - ".env*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Updated to use Node.js 20-compatible version
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # This action doesn't need to be updated
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3 # This action doesn't need to be updated
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: brianoflondon/v4vapp-frontend-v2
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest
      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0 # Updated to use Node.js 20-compatible version
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
